### ISSUE TITLE
Diff reports error but helm template works

### ISSUE THREAD

**Issue by eperdeme** [databus23/helm-diff#133]
Hello,

If I run my chart via 'helm template' it pases and looks fine, but if I try a helm diff it errors as below.

Values.yaml
```yaml
istio:
  kiali:
    enabled: true
    host: kiali.mydomain.com
    port: 20001
  grafana:
    enabled: true
    host: grafana.mydomain.com
    port: 3000
```

templates/istio.yaml
```yaml
{{- $fullName := include "istio-expose.fullname" . -}}
{{- $dot := . }}
{{- range $name, $data := .Values.istio }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $name }}-gateway
  labels:
    app.kubernetes.io/name: {{ include "istio-expose.name" $dot }}
    helm.sh/chart: {{ include "istio-expose.chart" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-{{ $fullName }}
      protocol: HTTP
    hosts:
    - {{ $data.host }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $name }}-vs
  labels:
    app.kubernetes.io/name: {{ include "istio-expose.name" $dot }}
    helm.sh/chart: {{ include "istio-expose.chart" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
spec:
  hosts:
  - {{ $data.host }}
  gateways:
  - {{ $name }}-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: {{ $name }}
        port:
          number: {{ $data.port }}
{{- end }}
```

helm diff upgrade istio-expose .  :
```shell
Error: render error in "istio-expose/templates/istio.yaml": template: istio-expose/templates/istio.yaml:23:14: executing "istio-expose/templates/istio.yaml" at <$data.host>: can't evaluate field host in type interface {}
render error in "istio-expose/templates/istio.yaml": template: istio-expose/templates/istio.yaml:23:14: executing "istio-expose/templates/istio.yaml" at <$data.host>: can't evaluate field host in type interface {}
Error: plugin "diff" exited with error
exit status 1
```

helm template .
```
helm template . 
---
# Source: istio-expose/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-istio-expose-test-connection"
  labels:
    app.kubernetes.io/name: istio-expose
    helm.sh/chart: istio-expose-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['release-name-istio-expose:80']
  restartPolicy: Never

---
# Source: istio-expose/templates/istio.yaml

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  labels:
    app.kubernetes.io/name: istio-expose
    helm.sh/chart: istio-expose-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-release-name-istio-expose
      protocol: HTTP
    hosts:
    - grafana.mydomain.com


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  labels:
    app.kubernetes.io/name: istio-expose
    helm.sh/chart: istio-expose-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  hosts:
  - grafana.mydomain.com
  gateways:
  - grafana-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: grafana
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  labels:
    app.kubernetes.io/name: istio-expose
    helm.sh/chart: istio-expose-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-release-name-istio-expose
      protocol: HTTP
    hosts:
    - kiali.mydomain.com


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  labels:
    app.kubernetes.io/name: istio-expose
    helm.sh/chart: istio-expose-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  hosts:
  - kiali.mydomain.com
  gateways:
  - kiali-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: kiali
        port:
          number: 20001
```
