### ISSUE TITLE
helm diff is not showing changes for a chart containing only Helm chart hooks.

### ISSUE THREAD

**Issue by jim-barber-he** [databus23/helm-diff#174]
The version of helm-diff I am using is:
```
$ helm plugin list | grep diff
diff   	3.0.0-rc.7	Preview helm upgrade changes as a diff 
```

If you have a chart that contains only helm hooks, then helm-diff does not see any changes.

E.g.
If you create a chart called `test` that has the following resource:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: '-5'
    helm.sh/hook: pre-install,pre-upgrade
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: test
          image: busybox:1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "echo testing 1 2 3; sleep 60"
```
And then run `helm diff upgrade --allow-unreleased test test` the result is:
```
$ helm diff upgrade --allow-unreleased test test
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
$
```
The hook is not shown in the output.
When using tools such as `helmfile apply` that run the diff first to determine if  they need to do anything, they see no changes and the chart will not be installed.

Removing the annotations so that the Job is no longer a Helm chart hook and running the command again, shows the changes:
```
$ helm diff upgrade --allow-unreleased test test
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
default, test, Job (batch) has been added:
- 
+ # Source: test/templates/test-hook.yaml
+ apiVersion: batch/v1
+ kind: Job
+ metadata:
+   name: test
+ spec:
+   template:
+     spec:
+       restartPolicy: Never
+       containers:
+         - name: test
+           image: busybox:1
+           imagePullPolicy: IfNotPresent
+           command:
+             - sh
+             - -c
+             - "echo testing 1 2 3; sleep 60"
$
```
However this is not suitable because the hook waits for the job to run to completion before Helm returns whereas using a plain Job will return as soon as the resource definition is created.
