### ISSUE TITLE
Truncate very large diff

### ISSUE THREAD

**Issue by nvanheuverzwijn** [databus23/helm-diff#192]
Is there a way to truncate very large diff ?
I am usually interested into what changed but not the rest of the file. For example, I would prefer this
```
  metadata:
    labels:
      app.kubernetes.io/instance: "data"
      app.kubernetes.io/name: "data"
      app.kubernetes.io/managed-by: "Helm"
-     helm.sh/chart: "1"
+     helm.sh/chart: "2"
```
over
```
kube-system, data, Service (v1) has changed:
  # Source: data/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/instance: "data"
      app.kubernetes.io/name: "data"
      app.kubernetes.io/managed-by: "Helm"
-     helm.sh/chart: "1"
+     helm.sh/chart: "2"
    name: service
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 80
        name: http
    selector:
      app.kubernetes.io/instance: "data"
      app.kubernetes.io/name: "data"
    type: "ClusterIP"
```

Is this acheivable ?
