### ISSUE TITLE
although there is no change in my chart but helm diff upgrade detect secret checksum changes at each time

### ISSUE THREAD

**Issue by emre141** [databus23/helm-diff#202]
I am using helm diff for rabbitmq-ha chart deployment. But although I made no changes on configmap , values.yaml or anything other files on the chart helm I got a few changes from following helm diff upgrade command

`$ HELM_NAMESPACE=$aks_namespace  helm diff upgrade mqttservice ./rabbitmq-ha -f  rabbitmq-ha/values.yaml -f rabbitmq-ha/values.${Environment}.yaml --namespace $aks_namespace`
And then I execute helm install upgrade following command that apply change my cluster on kubernetes.

`helm upgrade --install mqttservice ./rabbitmq-ha/ -f rabbitmq-ha/values.yaml -f rabbitmq-ha/values.${Environment}.yaml   --namespace $aks_namespace --debug --wait`

I expected i could not seen any result from helm diff and there was no update existing cluster.
I have got following changes will be apply from helm diff upgrade command

![image (1)](https://user-images.githubusercontent.com/13251823/78801426-5cc2a600-79c5-11ea-9e9b-d9f2064c155a.png)

There is a annotations under template spec.
```yaml
  template:
    metadata:
      labels:
        app: {{ template "rabbitmq-ha.name" . }}
        release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
{{- end }}
      annotations:
        {{- if not .Values.existingConfigMap }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if not .Values.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
```
Helm Diff Revision
root@cloudyanke:/opt/rabbitmq-azure# HELM_NAMESPACE=conn  helm diff revision mqttservice ./rabbitmq-ha
root@cloudyanke:/opt/rabbitmq-azure# HELM_NAMESPACE=conn  helm diff revision mqttservice ./rabbitmq-ha
