### ISSUE TITLE
Honor .Release.IsInstall

### ISSUE THREAD

**Issue by unfor19** [databus23/helm-diff#266]
### Use case

I'm creating dynamic environments which include a K8S Secret. If the secret doesn't exist ([.Release.IsInstall](https://helm.sh/docs/topics/charts/#predefined-values)) its data (mysql credentials) is automatically generated with [randAlphaNum](https://helm.sh/docs/chart_template_guide/function_list/#randalphanum-randalpha-randnumeric-and-randascii) and [b64enc](https://helm.sh/docs/chart_template_guide/function_list/#encoding-functions). If the secret exists, use the existing data (mysql credentials).

<details>

<summary>My Template - Expand/Collapse</summary>

`my-template.yaml`
```yaml
apiVersion: v1
kind: Secret
{{- $object_name := printf "%s-%s" .Release.Name "mysql-secret" }}
{{- $object_exists := (lookup "v1" "Secret" .Release.Namespace $object_name) }}
metadata:
  name: {{ $object_name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: database
data:
  {{- if .Release.IsInstall }}
  mysql_user: {{ "willywonka" | b64enc }}
  mysql_password: {{ randAlphaNum 20 | b64enc }}
  mysql_root_password: {{ randAlphaNum 20 | b64enc }}
  {{ else if $object_exists }}
  mysql_user: {{ index $object_exists.data "mysql_user" }}      
  mysql_password: {{ index $object_exists.data "mysql_password" }}
  mysql_root_password: {{ index $object_exists.data "mysql_root_password" }}
  {{ end }}
```

</details>

### The Issue

helm diff does not honor the `.Release.IsInstall` flag. I've also tried adding the `--reuse-values` flag and got the same results. 

I haven't changed the secrets and if I add `--show-secrets` I get the encoded secret values (instead of `20 bytes`) which means Helm is working properly behind the scenes and it gets the `data` from the K8S Secret if it exists.

```bash
$ helm diff upgrade my-app .

devops-sandbox, my-app-mysql-secret, Secret (v1) has changed:
...
- data:
-   mysql_password: '-------- # (20 bytes)'
-   mysql_root_password: '-------- # (20 bytes)'
-   mysql_user: '-------- # (8 bytes)'
```

### Things that I've tried with `helm template`

Using `helm template` generates new encoded values each time I that execute `helm template`.

```bash
$ helm template --release-name my-app .
# Don't worry the encoded values are random ;)
...
data:
  mysql_user: aGVsbG8Kwww=
  mysql_password: aHF3ZTc3s2pFTd5YZnZadWtOexY=
  mysql_root_password: a3RYODdrrkwrQ29hMVJufHNqbWi=
```

Adding the `--is-upgrade` flag sets the data to be empty, which means none of the rules `.Release.IsInstall` or `$object_exists` are true. So this flag might not work with Helm's [lookup function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function).

```bash
$ helm template --release-name my-app . --is-upgrade
...
data:
```
