### ISSUE TITLE
No diff returned despite changes

### ISSUE THREAD

**Issue by epitstickpan** [databus23/helm-diff#413]
```
❯ helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

❯ helm diff version
3.6.0
```

I have a single chart that always fails to run `helm diff upgrade` correctly. Assuming the info from `--debug` can be trusted it seems that it doesn't try to get the values from the correct namespace. `helm diff upgrade` seems to work fine for a number of other charts that I use. What other information can I give you?

```
❯ helm diff --color --show-secrets upgrade -n monitoring thechartname . --debug
Executing helm version
Executing helm get manifest thechartname --namespace monitoring
Executing helm get values thechartname --all --output yaml
Executing helm template thechartname . --namespace monitoring --values /tmp/existing-values2943739150 --validate --is-upgrade
Executing helm get hooks thechartname --namespace monitoring
```

**Comment by yajo** [comment]
I'm getting the same problem. In my case, the current release values are:

```yaml
csiRBDPluginVolumes: |
  - name: lib-modules
    hostPath:
      path: /run/current-system/kernel-modules/lib/modules/
  - name: host-nix
    hostPath:
      path: /nix
csiRBDPluginVolumeMounts: |
  - name: host-nix
    mountPath: /nix
    readOnly: true
csiCephFSPluginVolumes: |
  - name: lib-modules
    hostPath:
      path: /run/current-system/kernel-modules/lib/modules/
  - name: host-nix
    hostPath:
      path: /nix
csiCephFSPluginVolumeMounts: |
  - name: host-nix
    mountPath: /nix
    readOnly: true
```

However, they should be inside a `csi` top-level key, so the new values are:

```yaml
csi:
  # DOCS https://rook.io/docs/rook/v1.10/Getting-Started/Prerequisites/prerequisites/#nixos
  csiRBDPluginVolumes: |
    - name: lib-modules
      hostPath:
        path: /run/current-system/kernel-modules/lib/modules/
    - name: host-nix
      hostPath:
        path: /nix
  csiRBDPluginVolumeMounts: |
    - name: host-nix
      mountPath: /nix
      readOnly: true
  csiCephFSPluginVolumes: |
    - name: lib-modules
      hostPath:
        path: /run/current-system/kernel-modules/lib/modules/
    - name: host-nix
      hostPath:
        path: /nix
  csiCephFSPluginVolumeMounts: |
    - name: host-nix
      mountPath: /nix
      readOnly: true
```

Helm diff detects no changes, although it's completely changed.
