### ISSUE TITLE
--suppress-secrets not work since 3.2.0

### ISSUE THREAD

**Issue by yxxhero** [databus23/helm-diff#425]
--suppress-secrets not work since 3.2.0

but --show-secrets can show the diff between secrets.

example secert:

```
        apiVersion: v1
        kind: Secret
        metadata:
          name: registry-storage
          namespace: test
        stringData:
          config: |-
            azure:
              accountname: test
              accountkey: test
              container: test
              realm: test
```
