### ISSUE TITLE
helm diff randomly returns different result when using the --normalize-manifest flag

### ISSUE THREAD

**Issue by michael-pxr** [databus23/helm-diff#433]
Hi,
Every time I run `helm diff upgrade` with the `--normalize-manifest` flag I get different results.

I'm using the latest version:
```shell
± helm diff version
3.6.0
```

I've created a Chart that only contains the following template
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: diff-test
data:
  {{- range $key, $value := .Values.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
```
and the following `values.yaml` file:
```yaml
data:
  foo_1min_a: a1
  foo_5min_a: a5
  foo_15min_a: a15
  foo_24h_a: a24
  foo_1min_b: b1
  foo_5min_b: b5
  foo_15min_b: b15
  foo_24h_b: b24
  foo_1min_c: c1
  foo_5min_c: c5
  foo_15min_c: c15
  foo_24h_c: c24
  foo_1min_d: d1
  foo_5min_d: d5
  foo_15min_d: d15
  foo_24h_d: d24
```

I've installed the Chart by running
```shell
± helm install diff-test .
```

When I run `helm diff` I get one of the following results:
**1.**
```diff
± helm diff upgrade --normalize-manifests diff-test .
default, diff-test, ConfigMap (v1) has changed:
  apiVersion: v1
  data:
+   foo_5min_a: a5
+   foo_5min_b: b5
+   foo_5min_c: c5
+   foo_5min_d: d5
    foo_15min_a: a15
    foo_15min_b: b15
    foo_15min_c: c15
    foo_15min_d: d15
    foo_1min_a: a1
    foo_1min_b: b1
    foo_1min_c: c1
    foo_1min_d: d1
-   foo_5min_a: a5
-   foo_5min_b: b5
-   foo_5min_c: c5
-   foo_5min_d: d5
    foo_24h_a: a24
    foo_24h_b: b24
    foo_24h_c: c24
    foo_24h_d: d24
  kind: ConfigMap
  metadata:
    name: diff-test
```
**2.**
```diff
± helm diff upgrade --normalize-manifests diff-test .
default, diff-test, ConfigMap (v1) has changed:
  apiVersion: v1
  data:
-   foo_15min_a: a15
-   foo_15min_b: b15
-   foo_15min_c: c15
-   foo_15min_d: d15
    foo_1min_a: a1
    foo_1min_b: b1
    foo_1min_c: c1
    foo_1min_d: d1
    foo_5min_a: a5
    foo_5min_b: b5
    foo_5min_c: c5
    foo_5min_d: d5
+   foo_15min_a: a15
+   foo_15min_b: b15
+   foo_15min_c: c15
+   foo_15min_d: d15
    foo_24h_a: a24
    foo_24h_b: b24
    foo_24h_c: c24
    foo_24h_d: d24
  kind: ConfigMap
  metadata:
    name: diff-test
```
**3.**
```diff
± helm diff upgrade --normalize-manifests diff-test .
# No changes
```

I expected to always see no changes (result **3.**).
Do you know why I sometimes get result **1.** and **2.**?
Is there a way to always get result **3.**?
