### ISSUE TITLE
Diff shows + namespace when three-way-merge is used

### ISSUE THREAD

**Issue by Noksa** [databus23/helm-diff#445]
Hi.
My manifests in helm template don't contain `namespace` in metadata because it is substituted by helm automatically.

Thus, when I use helm diff with --three-way-merge flag, I see a lot of places that `namespace` is going to be added.

Is there a way to ignore `namespace` field in diff?

Example:
```yaml
test-test, test-test, Service (v1) has changed:
  apiVersion: v1
  kind: Service
  metadata:
    name: test-test
+  namespace: test-test
  spec:
    ports:
    - port: 80
      targetPort: 80
    selector:
      test-test: test-test
    type: ClusterIP
```
