### ISSUE TITLE
Ability to suppress specific metadata label/annotations 

### ISSUE THREAD

**Issue by jkroepke** [databus23/helm-diff#473]
Hi,

helm diff produces large diffs, if a helm chart upgrade is happening.

Since its common to put the chart version as label on each resource, Each resource has a diff at minimum.

![image](https://github.com/databus23/helm-diff/assets/1560587/388d6094-8291-4d38-9793-eb8e5e6cd0e7)

**Comment by jkroepke** [comment]
ref https://github.com/databus23/helm-diff/issues/392

**Comment by MrKich** [comment]
Is it possible to suppress lines not only in diff output, but in diff logic, too (e.g. do not return exit code 2 if all changes are only in suppressed lines) ?

**Comment by yypastushenko** [comment]
We frequently encounter unwanted changes in helm diff caused by dynamically injected fields (like caBundle added by cert-manager annotations). For example, in a MutatingWebhookConfiguration resource:
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-vault/vault-secrets-webhook-webhook-tls
webhooks:
  - clientConfig:
      caBundle: <base64-encoded-ca>
```
Here, the cert-manager webhook dynamically injects the caBundle field into clientConfig. Since this field is not present in the original Helm chart and is added at runtime, helm diff always shows changes, leading to unnecessary noise in CI/CD pipelines.

**Current Behavior:**
- helm-diff cannot exclude specific changes within a resource’s manifest.
- Only whole objects can be excluded using --skip-deployments, but this is too coarse-grained for our use case.

**Desired Behavior:**
- Similar to ArgoCD, provide the ability to exclude specific changes using JSONPath patterns.

For example, in ArgoCD, we can [configure exclusion](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration) as follows:
```
spec:
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: "MutatingWebhookConfiguration"
      jsonPointers:
        - "/webhooks/0/clientConfig/caBundle"
```
With such a feature in helm-diff, we could precisely exclude changes like caBundle without ignoring the entire resource.

**Why It Matters:**
Helm diff is often used in CI/CD pipelines to detect Infrastructure as Code (IaC) drift. However, it currently reports changes even when there are no actual updates to apply from IaC. This creates unnecessary noise, reduces the reliability of drift detection, and disrupts automation workflows.
