### ISSUE TITLE
HELM_DIFF_IGNORE_UNKNOWN_FLAGS doesn't ignore --atomic

### ISSUE THREAD

**Issue by frankwese** [databus23/helm-diff#535]
Hi,
I am trying to use helm diff in a github workflow. Therefore I added a step to prepare all helm arguments and pass these to either `helm diff upgrade` or `helm upgrade`.
Despite that I set 
```yaml
        - name: Show diff
          shell: bash
          env:
              FORCE_COLOR: '1'
              HELM_DIFF_COLOR: true
              HELM_DIFF_IGNORE_UNKNOWN_FLAGS: true
              HELM_DIFF_OUTPUT_CONTEXT: 1
          run: >
              helm diff upgrade ${{steps.helm_args.outputs.OUT}}
```
helm-diff complains about unknown flag: --atomic
Do I do something wrong?
