### ISSUE TITLE
Remote Logging in Airflow Helm string expected instead of bool

### ISSUE THREAD

**Issue by alvaromaroto** [databus23/helm-diff#641]
**Summary**

Helm Diff shows an error in Airflow Helm with `.Values.config.logging.remote_logging` because it expects a string instead of bool

**Error**

`Error: Failed to render chart: exit status 1: Error: template: airflow/templates/NOTES.txt:135:73: executing "airflow/templates/NOTES.txt" at <.Values.config.logging.remote_logging>: wrong type for value; expected string; got bool
`

My config is:

```yaml
config:
  core:
    hostname_callable: airflow.utils.net.get_host_ip_address
  celery:
    flower_url_prefix: ''  # Default value "/" was making it does not work
    worker_concurrency: 5
  logging:
    remote_base_log_folder: s3://XXXXX
    remote_log_conn_id: aws_default
    encrypt_s3_logs: false
    remote_logging: true
```

`remote_logging` only is rendered if I put "true" or "True" (string) instead of bool
